[package]
name = "robopoker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", features = [ "small_rng" ] }
colored = "2.0"
dialoguer = "0.11.0"
tokio = { version = "1.0", features = ["full"] }
petgraph = "0.6.5"
