[package]
name    = "robopoker"
version = "0.1.0"
edition = "2021"

[dependencies]
colored     = "2.0"
petgraph    = "0.6.5"
dialoguer   = "0.11.0"
rand        = { version = "0.8.5", features = [ "small_rng" ] }
tokio       = { version = "1.0", features = ["full"] }
sqlx        = { version = "0.8", features = ["runtime-tokio-native-tls", "postgres"] }

[dev-dependencies]
criterion = "0.5"


[[bench]]
name = "iterator"
harness = false