[package]
name    = "robopoker"
version = "0.1.0"
edition = "2021"

[dependencies]
colored         = "2.0"
petgraph        = "0.6.5"
dialoguer       = "0.11.0"
rand            = { version = "0.8.5", features = [ "small_rng" ] }
tokio           = { version = "1.0", features = ["full"] }
tokio-postgres  = "0.7.11"
futures         = "0.3"
bytes           = "1.0"
num_cpus        = "1.16.0"
log             = "0.4.22"
env_logger = "0.11.5"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "benchmarks"
harness = false
