services:
  robopoker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://username:password@postgres:5432/robopoker
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - robopoker
    volumes:
      - robopoker:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=robopoker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d robopoker"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=1536MB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "effective_cache_size=5GB"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "max_wal_size=1GB"
      - "-c"
      - "checkpoint_timeout=15min"
      - "-c"
      - "autovacuum=off"
      - "-c"
      - "fsync=off"
      - "-c"
      - "full_page_writes=off"
volumes:
  robopoker:
networks:
  robopoker:
    driver: bridge
