name: Rust
on:
  push:
    branches: ["main"]
jobs:
  build-test-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test --quiet --lib
      - name: Benchmark
        run: cargo bench --quiet --message-format short
